### PR TITLE
Require SETTINGS_H3_DATAGRAM and max_datagram_frame_size TP

### LINKED ISSUE #84: WT over HTTP/3 should require capsule support and datagram support explicitly
Per discussion at IETF 114, we should explicitly require support for each layer of capabilities that are needed. 

There was also a discussion about whether or not we needed to require datagram support, since requiring capsules technically means that you could use a datagram capsule and implementations may exist that do not want to have datagram support at all.

Documenting some of that discussion in replies to this issue, as well.

### PR DESCRIPTION
**Pull request by ekinnear**
Require SETTINGS_H3_DATAGRAM and max_datagram_frame_size TP

Closes #84

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]
Would this be easier to process as a list rather than multiple separate requirements?

**Review by DavidSchinazi — APPROVED** [review]
The list text in that comment isn't correct - the server shouldn't close the connection because it's legal for the client to not support datagrams if it only sends GETs and POSTs.

However, the text in this PR is correct. I propose we land the PR as-is and can make editorial changes later.

**Review by vasilvv — APPROVED** [review]

**Comment by ekinnear** [comment]
> The server shouldn't close the connection because it's legal for the client to not support datagrams if it only sends GETs and POSTs.

While technically true, I thought we'd said that we wanted to require all the features all of the time, but agreed, let's take that to an editorial issue if needed.

**Comment by DavidSchinazi** [comment]
My point is that the server could support both regular HTTP and WebTransport.
* If a client comes in without webtransport settings and only sends GETs, that's fine.
* If a client comes in with webtransport settings and makes a webtransport request, that's fine.
* If a client comes in without webtransport settings and makes a webtransport request, that's not fine. In that case the server needs to reject the webtransport request, not kill the connection.

**Comment by ekinnear** [comment]
Ah, that makes more sense, thank you :)

**Pull request merged**
